### ISSUE TITLE
Cant view images in the file manager

### ISSUE THREAD

**Issue by T9Air** [RickyDane/CoDriver#116]
Just a feature request. Most file managers allow you to see a small bit of a picture in the file manager itself, could you add that capability?

**Comment by RickyDane** [comment]
Hey @T9Air, this should be already available.
If I understand you correctly, you want a image preview in the directory panel?

Maybe you need to enable it in the settings:

![Screenshot 2024-08-15 at 08 07 45](https://github.com/user-attachments/assets/b72e4c72-e2d0-4208-b176-67a6102b1c70)

**Comment by RickyDane** [comment]
This is disabled by default, because it's a performance penalty if the file explorer hast to render images.
Maybe I should enable it by default? What do you think about that @T9Air?

**Comment by T9Air** [comment]
It would probably be better if it were enabled by default, as most file explorers do have it enabled.

**Comment by RickyDane** [comment]
I think that's a good idea. A friend of mine said the same thing so I think that's an option that should be enabled by default.
Thank for pointing it out!

I will close this comment as soon as I release the next version with this option enabled for new installs.

**Comment by RickyDane** [comment]
Closed with #121
