### ISSUE TITLE
[FR} enable configuration of shortcuts and launch path during installation

### ISSUE THREAD

**Issue by T9Air** [RickyDane/CoDriver#136]
I do not know if this is possible, but it would be great if you could configure the shortcuts and launch path during installation.

**Comment by RickyDane** [comment]
Hey @T9Air, thanks for mentioning it!
Currently it is not planned to configure those settings in the installer but I will keep an Eye on it and note it down so maybe we can ship this feature in a future release!

Closing issue, because it isn't planned yet.
