### ISSUE TITLE
Last modified time difference

### ISSUE THREAD

**Issue by no-1-noob** [RickyDane/CoDriver#66]
When comparing file modified dates on win10 i get a time difference of 2hrs.
Also the date formatting is not the same between files with some showing UTC some not. The top files were created by VIsualStudio and copied to this folder automatically, the lower ones are external donwloads.
![image](https://github.com/RickyDane/rdpFX/assets/91905916/5e5644f6-7439-43a0-9359-e376efb1499f)

**Comment by RickyDane** [comment]
I will look into it.

**Comment by RickyDane** [comment]
Closed as not planned
